### ISSUE TITLE
credentials

### ISSUE THREAD

**Issue by h02e56** [nko5/gitmatch#66]
About setting secret credentials we could put them on the root and git ignore them
Also maybe we can make a config folder on the root and move proper files there.
Is this a good way?

**Comment by repejota** [comment]
You can use your own credentials creating your own app. 
But sure we need to check if we are using a proper configuration for this values and is not hardcoded on the code.

**Comment by h02e56** [comment]
sip, i have allready created my application. i was thinking about putting my own credentials in the root credentials file and git ignore them. i will take a deeper  look on the auth process. :)
